---
- hosts: local
  connection: local
  #gather_facts: False
  vars:
     instance_type: t2.micro
     security_group: webservers_sg
     image: ami-03d64741867e7bb94
     keypair: aws1234_instance_Ansible
     region: us-east-2
     count: 1
  #vars_files:
  #  - ec2_key2.yml
  tasks:
    - name: Create a security group
      ec2_key:
        name: my1234_ansible_key
  #      aws_access_key: "{{ aws_access_key }}"
  #      aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
      register: key_value

    - local_action: copy content="{{key_value.key.private_key}}" dest=/app/test.pem
    #- debug:
    #      msg: "{{key_value.key.private_key}}"
    #      #var: key_value.key.private_key
